name: Publish artifacts

on:
  push:
    tags:
      - */aws/large
      - */aws/xlarge
      - */aws/xxlarge
      - */gcp/large
      - */gcp/xlarge
      - */gcp/xxlarge

jobs:
  publish:
    name: Publish artifacts
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract tag from ref
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF##*/}
    
    - name: Publish artifact based on cloud and size
      run: ./deploy.sh ${{ steps.get_version.outputs.VERSION }}

